'use client';

import { createElement, useMemo } from 'react';
import type { CSSProperties, HTMLAttributes } from 'react';
import { morphatar } from '@morphatar/core';
import type { MorphatarOptions } from '@morphatar/core';

export type { Animation, Mask, Variant } from '@morphatar/core';
export { morphatar, morphatarDataUri, morphatarPalette } from '@morphatar/core';

export interface MorphatarProps
  extends MorphatarOptions,
    Omit<HTMLAttributes<HTMLSpanElement>, 'color' | 'children' | 'dangerouslySetInnerHTML'> {}

/**
 * Renders a deterministic avatar for `seed`.
 *
 * The SVG is generated by `@morphatar/core` and injected with
 * `dangerouslySetInnerHTML` — the markup is built entirely from this library's
 * own numbers, and the only caller-supplied strings that reach it (`title`,
 * `colors`) are escaped or emitted as attribute values by the core.
 *
 * Generation is memoised on the options, so re-renders that don't change the
 * avatar don't re-run the PRNG.
 */
export function Morphatar({
  seed,
  variant,
  colors,
  background,
  mask,
  complexity,
  multicolor,
  animation,
  size,
  title,
  style,
  ...rest
}: MorphatarProps) {
  // Colors is an array; join it so a fresh literal on every render is not a
  // cache miss.
  const colorKey = colors ? colors.join(',') : '';

  const html = useMemo(
    () =>
      morphatar({
        seed,
        variant,
        colors: colorKey ? colorKey.split(',') : undefined,
        background,
        mask,
        complexity,
        multicolor,
        animation,
        size,
        title,
      }),
    [seed, variant, colorKey, background, mask, complexity, multicolor, animation, size, title],
  );

  const wrapperStyle = useMemo<CSSProperties>(() => {
    const box = size ?? '100%';
    return {
      display: 'inline-flex',
      width: typeof box === 'number' ? `${box}px` : box,
      height: typeof box === 'number' ? `${box}px` : 'auto',
      // Keeps a percentage-sized avatar square, which also gives the inner
      // `height="100%"` a definite box to resolve against.
      aspectRatio: '1 / 1',
      lineHeight: 0,
      flexShrink: 0,
      ...style,
    };
  }, [size, style]);

  return createElement('span', {
    ...rest,
    style: wrapperStyle,
    dangerouslySetInnerHTML: { __html: html },
  });
}

export default Morphatar;
